### ISSUE TITLE
Feature: log live tail

### ISSUE THREAD

**Issue by durzo** [logentries/lecli#16]
I'm loving the CLI, but by far the most important feature to me as a logentries customer is having the ability to live tail my logs without using the web UI.

It would be nice to specify -f (follow) to the recentevents options, similar to unix tail command.

**Comment by StephenHynes7** [comment]
I think that will be next on the cards once we have a suitable API for it, we want to make sure we are using as many the new RESTful API's we have versus the older API's that a lot of older scripts were based on. Once we have one for tail expect that to be added!

**Comment by durzo** [comment]
Thanks Stephen.

While we wait for this new API feature I have created a live tail CLI based on the current API that the web interface uses. It can be found at https://github.com/durzo/letail and supports named log keys if lecli is installed.

**Comment by stopal-r7** [comment]
@durzo @StephenHynes7  Live tail is a supported feature as of v1.0.0, enjoy :)
