### ISSUE TITLE
Lecli 3.4 and apiutils 2.7

### ISSUE THREAD

**Issue by VanOvermeire** [logentries/lecli#19]
So I installed the logentries cli using pip install. Lecli was installed under my python 3.4 folder. When I try to do anything, python complains about the syntax errors in apiutils (like missing brackets), which are clearly connected to that script being 2.7 and not 3.4. Upgrading apiutils didn't work, because it seems like there is no python 3 version (?).

Anything advice? Anything I'm doing wrong?

**Comment by StephenHynes7** [comment]
So currently lecli only supports Python 2.7 and not Python 3 hence the issues you are running into.  I don't think we have plans to support Python 3 at the moment though we would be happy to accept any PR's to make the code cross compatible.

**Comment by VanOvermeire** [comment]
Ok, thanks for your quick reply. Had to mess around a bit (both pip and pip3 were pointing to python 3), but got the script working.
