### ISSUE TITLE
codec can't encode character u'\xfc'

### ISSUE THREAD

**Issue by Erritmuller** [logentries/lecli#31]
This error comes when its trying to read the letter ü -

Full error: UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 7: ordinal not in range(128)

**Comment by stopal-r7** [comment]
hey @Erritmuller, which command is it? Looks like a simple encoding problem. There has been an improvement around encoding in REST API a few weeks ago, can you check if it still occurs?

**Comment by stopal-r7** [comment]
Closing as more information needed to reproduce the bug. Feel free to reopen it if you can provide more steps to reproduce.
