### ISSUE TITLE
Minor errors in generated config.ini template

### ISSUE THREAD

**Issue by agalauner-r7** [logentries/lecli#39]
When setting up lecli, I ran into two smaller errors in the generated config.ini created by https://github.com/rapid7/lecli/blob/master/lecli/api_utils.py#L43:

1. The `ro_api_key` is missing
2. The correct key name for the API endpoint is not `log_management_url` but `management_url`

lecli is goign to complain about missing keys when it's being run and this stuff is easy to fix manually, so this is a minor thing.

**Comment by stopal-r7** [comment]
Hey @agalauner-r7, thanks. That is a valid one, this should be fixed soon. I will be taking actions for this soon.

**Comment by stopal-r7** [comment]
This should be fixed now as of 0.7.5 version.

https://github.com/rapid7/lecli/pull/41
